<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.24" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Stripe.net" Version="50.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GapForge.Apllication\GapForge.Apllication.csproj" />
    <ProjectReference Include="..\GapForge.Core\GapForge.Core.csproj" />
    <ProjectReference Include="..\GapForge.Infrastructure\GapForge.Infrastructure.csproj" />
  </ItemGroup>

</Project>
